### ISSUE TITLE
Null reference occurs when loading glyphs and rendering text with a crafted TTF file

### ISSUE THREAD

**Issue by ch4rli3kop** [libsdl-org/SDL_ttf#199]
Hello, I found a **Segmentation Fault** in this project.

### Summary

Null reference occurs when loading glyphs and rendering text with a crafted TTF file.

### System Info

- Operating System: Ubuntu 20.04
- SDL_ttf version : the last commit 82f5cdb77efc48beb53e8f871ecbb51daa74c794

### Detailed

When `code1 = phy_font->chars[glyph1].char_code;` is executed, `phy_font->chars` is `0x0`. Since process references address null, the segmentation fault occurs.

```shell
gef➤  r crashed/access_violation_0000xxxxxxxxxE50_0000000000000000_1
Starting program: /home/ch4rli3kop/SDL/fuzz/OpenTTF crashed/access_violation_0000xxxxxxxxxE50_0000000000000000_1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
pfr_face_get_kerning (pfrface=0x5555555f1620, glyph1=0x0, glyph2=0x0, kerning=0x7fffffffd700) at external/freetype-2.11.1/src/pfr/pfrobjs.c:500
500	    code1 = phy_font->chars[glyph1].char_code;

[ Legend: Modified register | Code | Heap | Stack | String ]
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
$rax   : 0x0               
$rbx   : 0x00555555555860  →  <__libc_csu_init+0> endbr64 
$rcx   : 0x007fffffffd700  →  0x0000000000000000
$rdx   : 0x0               
$rsp   : 0x007fffffffd5b0  →  0x0000000000000000
$rbp   : 0x007fffffffd630  →  0x007fffffffd670  →  0x007fffffffd6c0  →  0x007fffffffd720  →  0x007fffffffd740  →  0x007fffffffd780  →  0x007fffffffd7b0  →  0x007fffffffd900
$rsi   : 0x0               
$rdi   : 0x005555555f1620  →  0x0000000000001f1f
$rip   : 0x007ffff7c86cb9  →  <pfr_face_get_kerning+157> mov eax, DWORD PTR [rax]
$r8    : 0x007ffff7c8235f  →  <pfr_get_kerning+0> endbr64 
$r9    : 0x007ffff7d5e62a  →  <hb_ft_get_glyph_h_kerning(hb_font_t*,+0> endbr64 
$r10   : 0x007ffff7d5e273  →  <hb_ft_get_glyph_h_advances(hb_font_t*,+0> endbr64 
$r11   : 0x007ffff78f2540  →  <pthread_mutex_unlock+0> endbr64 
$r12   : 0x00555555555300  →  <_start+0> endbr64 
$r13   : 0x007fffffffe020  →  0x0000000000000002
$r14   : 0x0               
$r15   : 0x0               
$eflags: [ZERO carry PARITY adjust sign trap INTERRUPT direction overflow RESUME virtualx86 identification]
$cs: 0x33 $ss: 0x2b $ds: 0x00 $es: 0x00 $fs: 0x00 $gs: 0x00 
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stack ────
0x007fffffffd5b0│+0x0000: 0x0000000000000000	 ← $rsp
0x007fffffffd5b8│+0x0008: 0x007fffffffd700  →  0x0000000000000000
0x007fffffffd5c0│+0x0010: 0x0000000000000000
0x007fffffffd5c8│+0x0018: 0x005555555f1620  →  0x0000000000001f1f
0x007fffffffd5d0│+0x0020: 0x00000000f7b85690
0x007fffffffd5d8│+0x0028: 0x007ffff7b85830  →  <X11_DestroyWindowFramebuffer+0> endbr64 
0x007fffffffd5e0│+0x0030: 0x007ffff7b8a9a0  →  <X11_GetDisplayUsableBounds+0> endbr64 
0x007fffffffd5e8│+0x0038: 0x007ffff7b8a950  →  <X11_GetDisplayDPI+0> endbr64 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── code:x86:64 ────
   0x7ffff7c86caf <pfr_face_get_kerning+147> mov    edx, DWORD PTR [rbp-0x6c]
   0x7ffff7c86cb2 <pfr_face_get_kerning+150> shl    rdx, 0x4
   0x7ffff7c86cb6 <pfr_face_get_kerning+154> add    rax, rdx
 → 0x7ffff7c86cb9 <pfr_face_get_kerning+157> mov    eax, DWORD PTR [rax]
   0x7ffff7c86cbb <pfr_face_get_kerning+159> mov    DWORD PTR [rbp-0x4c], eax
   0x7ffff7c86cbe <pfr_face_get_kerning+162> mov    rax, QWORD PTR [rbp-0x10]
   0x7ffff7c86cc2 <pfr_face_get_kerning+166> mov    rax, QWORD PTR [rax+0xc0]
   0x7ffff7c86cc9 <pfr_face_get_kerning+173> mov    edx, DWORD PTR [rbp-0x70]
   0x7ffff7c86ccc <pfr_face_get_kerning+176> shl    rdx, 0x4
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── source:external/freety[...].c+500 ────
    495	     /* convert glyph indices to character codes */
    496	     if ( glyph1 > phy_font->num_chars ||
    497	          glyph2 > phy_font->num_chars )
    498	       goto Exit;
    499	 
 →  500	     code1 = phy_font->chars[glyph1].char_code;
    501	     code2 = phy_font->chars[glyph2].char_code;
    502	     pair  = PFR_KERN_INDEX( code1, code2 );
    503	 
    504	     /* now search the list of kerning items */
    505	     {
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, Name: "OpenTTF", stopped 0x7ffff7c86cb9 in pfr_face_get_kerning (), reason: SIGSEGV
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
gef➤  bt
#0  pfr_face_get_kerning (pfrface=0x5555555f1620, glyph1=0x0, glyph2=0x0, kerning=0x7fffffffd700) at external/freetype-2.11.1/src/pfr/pfrobjs.c:500
#1  0x00007ffff7c823a5 in pfr_get_kerning (pfrface=0x5555555f1620, left=0x0, right=0x0, avector=0x7fffffffd700) at external/freetype-2.11.1/src/pfr/pfrdrivr.c:39
#2  0x00007ffff7c48b72 in FT_Get_Kerning (face=0x5555555f1620, left_glyph=0x0, right_glyph=0x0, kern_mode=0x1, akerning=0x7fffffffd700) at external/freetype-2.11.1/src/base/ftobjs.c:3496
#3  0x00007ffff7d5e691 in hb_ft_get_glyph_h_kerning (font=0x555555ec4380, font_data=0x555555eb7120, left_glyph=0x0, right_glyph=0x0, user_data=0x0) at external/harfbuzz-2.8.0/src/hb-ft.cc:425
#4  0x00007ffff7d5b328 in hb_font_t::get_glyph_h_kerning (this=0x555555ec4380, left_glyph=0x0, right_glyph=0x0) at external/harfbuzz-2.8.0/src/hb-font.hh:313
#5  0x00007ffff7d5b6c2 in hb_font_t::get_glyph_kerning_for_direction (this=0x555555ec4380, first_glyph=0x0, second_glyph=0x0, direction=HB_DIRECTION_LTR, x=0x7fffffffd7a4, y=0x7fffffffd7a4) at external/harfbuzz-2.8.0/src/hb-font.hh:540
#6  0x00007ffff7e5bcfc in hb_ot_shape_fallback_kern_driver_t::get_kerning (this=0x7fffffffd940, first=0x0, second=0x0) at external/harfbuzz-2.8.0/src/hb-ot-shape-fallback.cc:473
#7  0x00007ffff7e5bf40 in OT::hb_kern_machine_t<hb_ot_shape_fallback_kern_driver_t>::kern (this=0x7fffffffd950, font=0x555555ec4380, buffer=0x555555ea49f0, kern_mask=0x2, scale=0x0) at external/harfbuzz-2.8.0/src/hb-kern.hh:79
#8  0x00007ffff7e520e6 in _hb_ot_shape_fallback_kern (plan=0x555555ed2b80, font=0x555555ec4380, buffer=0x555555ea49f0) at external/harfbuzz-2.8.0/src/hb-ot-shape-fallback.cc:507
#9  0x00007ffff7e5f2bf in hb_ot_shape_plan_t::position (this=0x555555ed2b80, font=0x555555ec4380, buffer=0x555555ea49f0) at external/harfbuzz-2.8.0/src/hb-ot-shape.cc:274
#10 0x00007ffff7e610f5 in hb_ot_position_complex (c=0x7fffffffda70) at external/harfbuzz-2.8.0/src/hb-ot-shape.cc:1014
#11 0x00007ffff7e612b0 in hb_ot_position (c=0x7fffffffda70) at external/harfbuzz-2.8.0/src/hb-ot-shape.cc:1057
#12 0x00007ffff7e6169a in hb_ot_shape_internal (c=0x7fffffffda70) at external/harfbuzz-2.8.0/src/hb-ot-shape.cc:1131
#13 0x00007ffff7e617be in _hb_ot_shape (shape_plan=0x555555ed2b20, font=0x555555ec4380, buffer=0x555555ea49f0, features=0x0, num_features=0x0) at external/harfbuzz-2.8.0/src/hb-ot-shape.cc:1154
#14 0x00007ffff7e6f982 in _hb_shape_plan_execute_internal (shape_plan=0x555555ed2b20, font=0x555555ec4380, buffer=0x555555ea49f0, features=0x0, num_features=0x0) at external/harfbuzz-2.8.0/src/hb-shaper-list.hh:42
#15 0x00007ffff7e6fa31 in hb_shape_plan_execute (shape_plan=0x555555ed2b20, font=0x555555ec4380, buffer=0x555555ea49f0, features=0x0, num_features=0x0) at external/harfbuzz-2.8.0/src/hb-shape-plan.cc:453
#16 0x00007ffff7e70a95 in hb_shape_full (font=0x555555ec4380, buffer=0x555555ea49f0, features=0x0, num_features=0x0, shaper_list=0x0) at external/harfbuzz-2.8.0/src/hb-shape.cc:139
#17 0x00007ffff7e70ae1 in hb_shape (font=0x555555ec4380, buffer=0x555555ea49f0, features=0x0, num_features=0x0) at external/harfbuzz-2.8.0/src/hb-shape.cc:167
#18 0x00007ffff7c2eaed in TTF_Size_Internal (font=0x555555edc9a0, text=0x7fffffffdce0 "TV", str_type=STR_UTF8, w=0x7fffffffdd28, h=0x7fffffffdd2c, xstart=0x7fffffffdd20, ystart=0x7fffffffdd24, measure_width=0x0, extent=0x0, count=0x0) at SDL_ttf.c:2972
#19 0x00007ffff7c2f53b in TTF_Render_Internal (font=0x555555edc9a0, text=0x7fffffffdce0 "TV", str_type=STR_TEXT, fg=..., bg=..., render_mode=RENDER_SOLID) at SDL_ttf.c:3214
#20 0x00007ffff7c2f73a in TTF_RenderText_Solid (font=0x555555edc9a0, text=0x555555556035 "TV", fg=...) at SDL_ttf.c:3266
#21 0x00005555555555f6 in render_ttf(file=0x7fffffffe37f "crashed/access_violation_0000xxxxxxxxxE50_", '0' <repeats 16 times>, "_1", mRenderer=0x55555566dba0) at OpenTTF.cpp:33
#22 0x000055555555582e in main (argc=0x2, argv=0x7fffffffe028) at OpenTTF.cpp:97
```

### Reproduce

compile the below code and run the program with a crafted TTF file. A crafted TTF file link is [here](https://drive.google.com/file/d/1tb-jnRccXmz42wQrR_bKPCIUdCQjpzCN/view?usp=sharing)

#### main.cpp

```
#include <cstdlib>
#include "SDL.h"
#include "SDL_ttf.h"

#pragma comment (lib, "SDL2")
#pragma comment (lib, "SDL2main")
#pragma comment (lib, "SDL2_ttf")


#define WIN_W 0x400
#define WIN_H 0x300

void render_ttf(char* file, SDL_Renderer* mRenderer) {
	TTF_Font* font;
	char buf[0x100] = {0,};
	if (TTF_Init() == -1) {
		SDL_Log("Failed to init ttf : %s", SDL_GetError());
		return;
	}

	font = TTF_OpenFont(file, 40);
	if (!font) {
		SDL_Log("Failed to open font : %s", SDL_GetError());
		return;
	}

	SDL_Color color = { 111, 111, 255 };
	SDL_Surface* surface = TTF_RenderText_Solid(font, "TV", color);
	SDL_Texture* texture = SDL_CreateTextureFromSurface(mRenderer, surface);
	int W = 0, H = 0;
	SDL_QueryTexture(texture, NULL, NULL, &W, &H);
	SDL_Rect dstrect = { 0, 0, W, H };
	SDL_RenderCopy(mRenderer, texture, NULL, &dstrect);

	SDL_RenderPresent(mRenderer);

/*	SDL_Event event; 
	int done = 0; 
	while (!done) {
		SDL_PollEvent(&event); 
		if (event.type == SDL_QUIT) 
		{ done = 1; } 
	}
*/
	SDL_DestroyTexture(texture);
	SDL_FreeSurface(surface);

	TTF_CloseFont(font);
	TTF_Quit();
}

int main(int argc, char* argv[]) {

	SDL_Window* mWindow;
	SDL_Renderer* mRenderer;

	int sdlResult = SDL_Init(SDL_INIT_VIDEO);
	if (sdlResult) {
		SDL_Log("Unable to initialize SDL: %s", SDL_GetError());
		return false;
	}

	mWindow = SDL_CreateWindow(
		"SDL Font Test",
		100,
		100,
		WIN_W,
		WIN_H,
		SDL_WINDOW_RESIZABLE
	);

	if (!mWindow) {
		SDL_Log("Failed to create window : %s", SDL_GetError());
		return false;
	}

	mRenderer = SDL_CreateRenderer(
		mWindow,
		-1,
		SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC
	);

	if (!mRenderer) {
		SDL_Log("Failed to render window : %s", SDL_GetError());
		return false;
	}

	SDL_SetRenderDrawColor(mRenderer, 255, 255, 255, SDL_ALPHA_OPAQUE); 
	SDL_RenderClear(mRenderer); 

	render_ttf(argv[1], mRenderer);

	SDL_DestroyRenderer(mRenderer);
	SDL_DestroyWindow(mWindow);
	SDL_Quit();
}
```

#### compile & run

```
ch4rli3kop@ubuntu:~/SDL/fuzz$ g++ -o OpenTTF OpenTTF.cpp -D_REENTRANT -I/usr/local/include/SDL2 -L/usr/local/lib -lSDL2_ttf -Wl,-rpath,/usr/local/lib -Wl,--enable-new-dtags -lSDL2
ch4rli3kop in [~/SDL/fuzz] 9:26:35 › ./OpenTTF crashed/access_violation_0000xxxxxxxxxE50_0000000000000000_1
[1]    180722 segmentation fault (core dumped)  ./OpenTTF crashed/access_violation_0000xxxxxxxxxE50_0000000000000000_1
```

**Comment by sezero** [comment]
Unless I'm missing something, the issue is in freetype library and should be reported there: https://gitlab.freedesktop.org/freetype

**Comment by slouken** [comment]
Yeah, we can't validate font files that could cause FreeType to crash.
